apiVersion: v1
kind: PersistentVolume
metadata:
 name: nis-host-pv
spec:
 capacity:
   storage: 256Mi
 volumeMode: Filesystem
 storageClassName: standard
 accessModes:
   - ReadWriteOnce
 hostPath:
   path: /nis-data
   type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: nis-host-pvc
spec:
 volumeName: nis-host-pv
 accessModes:
   - ReadWriteOnce
 storageClassName: standard
 resources:
   requests:
     storage: 256Mi
