apiVersion: apps/v1
kind: Deployment
metadata:
  name: bg-library-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bg-library
  template:
    metadata:
      labels:
        app: bg-library
    spec:
      containers:
        - name: bg-library
          image: nikolavukicalt/local-lib:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: bg-library-config
        - name: bg-db
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: bg-db
      volumes:
        - name: bg-db
          persistentVolumeClaim:
            claimName: bg-host-pvc
