apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-library-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ns-library
  template:
    metadata:
      labels:
        app: ns-library
    spec:
      containers:
        - name: ns-library
          image: nikolavukicalt/local-lib:v1
          ports:
            - containerPort: 8081
        - name: ns-db
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: ns-db
      volumes:
        - name: ns-db
          persistentVolumeClaim:
            claimName: ns-host-pvc
