name: docker image ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Central library image build
      run: |
        docker build -t nikolavukicalt/central-lib:v1 ./library-app/central

    - name: Central library image push
      run: docker push nikolavukicalt/central-lib:v1

    - name: Local library image build
      run: |
        docker build -t nikolavukicalt/local-lib:v1 ./library-app/local

    - name: Local library image push
      run: docker push nikolavukicalt/local-lib:v1
