name: docker image ci

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}

    - name: Central library image build
      run: |
        docker build -t nikolavukicalt/central-lib:v1 ./library-app/central

    - name: Central library image push
      run: docker push nikolavukicalt/central-lib:v1

    - name: Local library image build
      run: |
        docker build -t nikolavukicalt/local-lib:v1 ./library-app/local

    - name: Local library image push
      run: docker push nikolavukicalt/local-lib:v1
